"""pyclif — PYthon Command Line Interface Framework"""

__app_name__ = "pyclif"
__version__ = "0.3.0"

from click_extra import (
    BOOL,
    FLOAT,
    INT,
    STRING,
    UUID,
    Abort,
    BadParameter,
    Choice,
    ClickException,
    DateTime,
    File,
    FloatRange,
    IntRange,
    TimerOption,
    Tuple,
    UsageError,
    argument,
    confirm,
    confirmation_option,
    echo,
    get_current_context,
    make_pass_decorator,
    pass_context,
    pass_obj,
    password_option,
    prompt,
    secho,
    style,
    unstyle,
    version_option,
)
from click_extra import (
    Path as ClickPath,
)

from .core.classes import CustomConfigOption, PyclifGroup, PyclifOption
from .core.context import BaseContext
from .core.decorators import (
    app_group,
    command,
    group,
    option,
    output_filter_option,
    pagination_options,
    returns_response,
)
from .core.interfaces import BaseInterface
from .core.log import (
    PYCLIF_LOG_LEVELS,
    TRACE,
    RichExtraFormatter,
    RichExtraStreamHandler,
    SecretsMasker,
    add_trace_method,
    configure_rich_logging,
    get_configured_logger,
    get_logger,
    logger,
)
from .core.mixins import (
    GlobalOptionsMixin,
    HandleResponseMixin,
    OutputFormatMixin,
    RichHelpersMixin,
)
from .core.models import BaseModel
from .core.output import (
    BaseRenderer,
    CliTable,
    CliTableColumn,
    ExceptionTable,
    ExitCode,
    OperationResult,
    PaginatedResponse,
    Response,
    ResponseRenderer,
)

__all__ = [
    "__app_name__",
    "__version__",
    # methods
    "app_group",
    "group",
    "command",
    "option",
    # click_extra re-exports
    "argument",
    "pass_context",
    "pass_obj",
    "make_pass_decorator",
    "get_current_context",
    "Choice",
    "ClickPath",
    "File",
    "INT",
    "FLOAT",
    "BOOL",
    "STRING",
    "UUID",
    "DateTime",
    "Tuple",
    "IntRange",
    "FloatRange",
    "echo",
    "secho",
    "style",
    "unstyle",
    "confirm",
    "prompt",
    "ClickException",
    "BadParameter",
    "UsageError",
    "Abort",
    "TimerOption",
    "version_option",
    "confirmation_option",
    "password_option",
    "output_filter_option",
    "pagination_options",
    "returns_response",
    "get_logger",
    "logger",
    "add_trace_method",
    "get_configured_logger",
    "configure_rich_logging",
    # class
    "BaseContext",
    "BaseModel",
    "ExitCode",
    "OperationResult",
    "PaginatedResponse",
    "Response",
    "BaseInterface",
    "BaseRenderer",
    "ResponseRenderer",
    "CliTable",
    "CliTableColumn",
    "ExceptionTable",
    "CustomConfigOption",
    "PyclifGroup",
    "PyclifOption",
    "GlobalOptionsMixin",
    "HandleResponseMixin",
    "OutputFormatMixin",
    "RichHelpersMixin",
    "RichExtraFormatter",
    "RichExtraStreamHandler",
    "SecretsMasker",
    # Constants
    "PYCLIF_LOG_LEVELS",
    "TRACE",
]
